export const NEWPLUGIN611_GET__READ = "NEWPLUGIN611_GET__READ"
export const NEWPLUGIN611_GET__READ_SUCCEEDED =
  "NEWPLUGIN611_GET__READ_SUCCEEDED"
export const NEWPLUGIN611_GET__READ_FAILED = "NEWPLUGIN611_GET__READ_FAILED"
