# Generated by Django 2.2.15 on 2020-08-06 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_customtext_tests"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customtext", old_name="tests", new_name="testsghhh",
        ),
    ]
