# Generated by Django 2.2.15 on 2020-08-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_remove_customtext_title"),
    ]

    operations = [
        migrations.RemoveField(model_name="homepage", name="body",),
        migrations.AddField(
            model_name="homepage",
            name="body1",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
