# Generated by Django 2.2.15 on 2020-08-06 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_auto_20200806_1132"),
    ]

    operations = [
        migrations.RenameField(
            model_name="homepage", old_name="body1", new_name="body11",
        ),
    ]
