# Generated by Django 2.2.15 on 2020-08-06 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200806_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customtext',
            old_name='testsghhh',
            new_name='test',
        ),
    ]
